import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/src/components/NavBar";



export const metadata: Metadata = {
  title: "Çocuk Aklı",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
         <NavBar />

        {children}
      </body>
    </html>
  );
}
