import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/src/components/navBar/NavBar";
import { cookies } from "next/headers";




export const metadata: Metadata = {
  title: "Çocuk Aklı",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

const cookieStore = await cookies();
const isLoggedIn = cookieStore.has("session");


  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
(function () {
  try {
    const stored = localStorage.getItem("theme");
    const prefersDark = window.matchMedia("(prefers-color-scheme: dark)").matches;
    const theme = stored || (prefersDark ? "dark" : "light");
    document.documentElement.setAttribute("data-theme", theme);
  } catch (_) {}
})();
            `,
          }}
        />
      </head>
      <body>
        <NavBar isLoggedIn={isLoggedIn}/>
        {children}
      </body>
    </html>
  );
}