import type { Metadata } from "next";
import Breadcrumbs from "@/src/components/layout/Breadcrumbs";
import PageTitle from "@/src/components/layout/PageTitle";




export const metadata: Metadata = {
  title: "EnBilet - Yönetici Paneli",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

 <>
 <Breadcrumbs></Breadcrumbs>
 <PageTitle></PageTitle>

<div className="my-8">
      <section className="admin-layout">
      {children}
    </section>
        </div>
</>
  );
}
