import type { Metadata } from "next";
import "src/app/globals.css";
import NavBar from "@/src/components/NavBar";



export const metadata: Metadata = {
  title: "Çocuk Aklı",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

 <>

        {children}
</>
  );
}
